(define (problem cake-bake-a)
    (:domain bake-cake)
    (:objects bowl flour sugar vanillia milk bakingPowder egg)
    (:init (isBowl bowl) (free bowl)
        (isFlour flour) (hasEnough flour)
        (isSugar sugar) (hasEnough sugar)
        (isVanillia vanillia) (hasEnough vanillia)
        (isMilk milk) (hasEnough milk)
        (isBakingPowder bakingPowder) (hasEnough bakingPowder)
        (isEgg egg) (hasEnough egg))
    (:goal (and (added flour bowl) (added sugar bowl)
                (added vanillia bowl) (added milk bowl)
                (added bakingPowder bowl) (added egg bowl)
            )
    )
)