(define (problem cake-bake-a)
    (:domain bake-cake)
    (:objects bowl flour sugar vanillia milk bakingPowder egg oil banana chocolate strawberry pan)
    (:init (isPan pan) (free pan)
        (isBowl bowl) (free bowl)
        (isFlour flour) (hasEnough flour)
        (isSugar sugar) (hasEnough sugar)
        (isVanillia vanillia) (hasEnough vanillia)
        (isMilk milk) (hasEnough milk)
        (isBakingPowder bakingPowder) (hasEnough bakingPowder)
        (isEgg egg) (hasEnough egg)
        (isOil oil) (hasEnough oil)
        (isBanana banana) (hasEnough banana)
        (isChocolate chocolate) (hasEnough chocolate)
        (isStrawberry strawberry) (hasEnough strawberry)
    )
    (:goal (and (isFilled pan) (bananaAdded bowl) (chocolateAdded bowl) (strawberryAdded bowl))
    )
)