(define (domain bake-cake)
    (:requirements :strips)
    (:predicates
            (isBowl ?b)
            (isPan ?p)
            (isFlour ?f)
            (isSugar ?s)
            (isVanillia ?v)
            (isMilk ?m)
            (isBakingPowder ?bp)
            (isEgg ?e)
            (isOil ?o)
            (isBanana ?bf)
            (isChocolate ?cf)
            (isStrawberry ?sf)
            (hasEnough ?ingredient)
            (free ?b)
            (basesAdded ?mixture)
            (readyToCook ?mixture)
            (bananaAdded ?bowl)
            (chocolateAdded ?bowl)
            (strawberryAdded ?bowl)
            (isMixed ?b)
            (isFilled ?p))
    (:action add-base-ingredients
        :parameters (?bowl ?flour ?sugar ?vanillia ?milk ?bakingPowder ?egg ?oil)
        :precondition (and (isBowl ?bowl) (free ?bowl)
            (isFlour ?flour) (hasEnough ?flour)
            (isSugar ?sugar) (hasEnough ?sugar)
            (isVanillia ?vanillia) (hasEnough ?vanillia)
            (isMilk ?milk) (hasEnough ?milk)
            (isBakingPowder ?bakingPowder) (hasEnough ?bakingPowder)
            (isEgg ?egg) (hasEnough ?egg)
            (isOil ?oil) (hasEnough ?oil))
        :effect (and (not (free ?bowl))
            (not (hasEnough ?flour))
            (not (hasEnough ?sugar))
            (not (hasEnough ?vanillia))
            (not (hasEnough ?milk))
            (not (hasEnough ?bakingPowder))
            (not (hasEnough ?egg))
            (not (hasEnough ?oil))
            (basesAdded ?bowl)
        )
    )
    
    (:action add-banana
        :parameters (?bowl ?banana)
        :precondition (and (isBanana ?banana) (hasEnough ?banana) (basesAdded ?bowl))
        :effect (and (bananaAdded ?bowl) (not (hasEnough ?banana)))
    )
        
    (:action add-chocolate
        :parameters (?bowl ?chocolate)
        :precondition (and (isChocolate ?chocolate) (hasEnough ?chocolate) (basesAdded ?bowl))
        :effect (and (chocolateAdded ?bowl) (not (hasEnough ?chocolate)))
    )
    
    (:action add-strawberry
        :parameters (?bowl ?strawberry)
        :precondition (and (isStrawberry ?strawberry) (hasEnough ?strawberry) (basesAdded ?bowl))
        :effect (and (strawberryAdded ?bowl) (not (hasEnough ?strawberry)))
    )
    
    (:action prepare-mix-to-cook
        :parameters (?bowl ?pan)
        :precondition (and (isMixed ?bowl) (isPan ?pan) (free ?pan))
        :effect (and (free ?bowl) (isFilled ?pan))
    )
    
    (:action mix-mixture
        :parameters (?bowl)
        :precondition (and (not (free ?bowl)) (basesAdded ?bowl))
        :effect (isMixed ?bowl)
    )
    
)
